#!/usr/bin/env node
const request = require('request');

API_KEY = 'b972c7ca44dda72a5b482052b1f5e13470e01477f3fb97c85d5313b3c112627073481104fec2fb1a0cc9d84c2212474c0cbe7d8e59d7b95c7cb32a1133f778abd1857bf934ba06647fda4f59e878d164'
URL = 'https://fourtytwowords.herokuapp.com/'
PLAY_ENDPOINT = 'words/randomWord'

var args = process.argv.slice(2);

function sendReq(endpoint, words) {
	url = URL + endpoint + '?api_key=' + API_KEY;
	request.get(url, function(request, response) {
		// console.log(response.body);
	});
}

switch(args[0]) {
	case 'play':
		console.log("Game under development. Please try later");
		sendReq(PLAY_ENDPOINT, null);
		break;
	default:
		console.log("Invalid argument.");
		break;
}
